// Dark tactical base map on OpenFreeMap's OpenMapTiles vector tiles. MapLibre draws the ground,
// roads, labels and near-black building bodies (which hide streets behind them); the holographic
// canvas adds light on top.
const FONT = ['Noto Sans Regular'];
const FONT_BOLD = ['Noto Sans Bold'];
const FONT_ITALIC = ['Noto Sans Italic'];

const cls = (...v) => ['in', ['coalesce', ['get', 'class'], ''], ['literal', v]];

export function buildStyle() {
  return {
    version: 8,
    glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
    sources: {
      omt: {
        type: 'vector',
        url: 'https://tiles.openfreemap.org/planet',
        attribution:
          '<a href="https://openfreemap.org" target="_blank" rel="noopener">OpenFreeMap</a> <a href="https://www.openmaptiles.org/" target="_blank" rel="noopener">© OpenMapTiles</a> Data <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a>',
      },
      imagery: {
        type: 'raster',
        tiles: ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],
        tileSize: 256,
        maxzoom: 19,
        attribution: 'Imagery © Esri, Maxar, Earthstar Geographics',
      },
    },
    layers: [
      { id: 'bg', type: 'background', paint: { 'background-color': '#02070b' } },
      {
        id: 'imagery',
        type: 'raster',
        source: 'imagery',
        layout: { visibility: 'none' },
        paint: { 'raster-saturation': -0.75, 'raster-brightness-max': 0.5, 'raster-contrast': 0.2, 'raster-hue-rotate': 190 },
      },
      {
        id: 'landcover-green',
        type: 'fill',
        source: 'omt',
        'source-layer': 'landcover',
        filter: cls('grass', 'wood', 'wetland', 'scrub', 'farmland'),
        paint: { 'fill-color': '#04160f', 'fill-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0.5, 14, 0.9] },
      },
      {
        id: 'landuse-green',
        type: 'fill',
        source: 'omt',
        'source-layer': 'landuse',
        filter: cls('cemetery', 'pitch', 'playground', 'park', 'garden', 'allotments'),
        paint: { 'fill-color': '#04140e', 'fill-opacity': 0.85 },
      },
      {
        id: 'landuse-urban',
        type: 'fill',
        source: 'omt',
        'source-layer': 'landuse',
        filter: cls('residential', 'commercial', 'industrial', 'retail'),
        maxzoom: 13,
        paint: { 'fill-color': '#061019', 'fill-opacity': 0.8 },
      },
      {
        id: 'water',
        type: 'fill',
        source: 'omt',
        'source-layer': 'water',
        filter: ['!=', ['get', 'brunnel'], 'tunnel'],
        paint: { 'fill-color': '#031621' },
      },
      {
        id: 'water-edge',
        type: 'line',
        source: 'omt',
        'source-layer': 'water',
        filter: ['!=', ['get', 'brunnel'], 'tunnel'],
        paint: {
          'line-color': '#2b9fd0',
          'line-width': ['interpolate', ['linear'], ['zoom'], 9, 0.4, 15, 1.4, 18, 2.4],
          'line-opacity': 0.75,
        },
      },
      {
        id: 'waterway',
        type: 'line',
        source: 'omt',
        'source-layer': 'waterway',
        paint: { 'line-color': '#11607f', 'line-width': ['interpolate', ['linear'], ['zoom'], 10, 0.5, 16, 2] },
      },
      {
        id: 'aeroway',
        type: 'line',
        source: 'omt',
        'source-layer': 'aeroway',
        filter: cls('runway', 'taxiway'),
        paint: { 'line-color': '#173c4d', 'line-width': ['interpolate', ['exponential', 1.6], ['zoom'], 10, 1, 16, 30] },
      },
      {
        id: 'rail',
        type: 'line',
        source: 'omt',
        'source-layer': 'transportation',
        filter: ['all', cls('rail', 'transit'), ['!=', ['get', 'brunnel'], 'tunnel']],
        paint: { 'line-color': '#1e4a5e', 'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 16, 1.4], 'line-dasharray': [2, 2] },
      },
      {
        id: 'roads-minor',
        type: 'line',
        source: 'omt',
        'source-layer': 'transportation',
        filter: cls('minor', 'service', 'track', 'path', 'pedestrian'),
        minzoom: 12.5,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': ['match', ['coalesce', ['get', 'class'], ''], 'path', '#0a2230', 'pedestrian', '#0c2a39', '#0e2c3b'],
          'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 13, 0.4, 16, 2.2, 18, 7],
        },
      },
      {
        id: 'roads-major-glow',
        type: 'line',
        source: 'omt',
        'source-layer': 'transportation',
        filter: cls('motorway', 'trunk', 'primary', 'secondary'),
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': '#1aa6d6',
          'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 9, 2, 14, 7, 18, 30],
          'line-blur': ['interpolate', ['linear'], ['zoom'], 9, 2, 16, 10],
          'line-opacity': 0.16,
        },
      },
      {
        id: 'roads-major',
        type: 'line',
        source: 'omt',
        'source-layer': 'transportation',
        filter: cls('motorway', 'trunk', 'primary', 'secondary', 'tertiary'),
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': ['match', ['coalesce', ['get', 'class'], ''], 'motorway', '#4fd4ff', 'trunk', '#39bfe9', 'primary', '#2ba1c9', 'secondary', '#1f7fa1', '#185f78'],
          'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 9, 0.4, 14, 1.3, 18, 5],
          'line-opacity': 0.9,
        },
      },
      {
        id: 'bldg-flat',
        type: 'fill',
        source: 'omt',
        'source-layer': 'building',
        maxzoom: 13.4,
        paint: { 'fill-color': '#0a2230', 'fill-opacity': 0.6 },
      },
      {
        id: 'bldg-3d',
        type: 'fill-extrusion',
        source: 'omt',
        'source-layer': 'building',
        minzoom: 13,
        filter: ['!=', ['get', 'hide_3d'], true],
        paint: {
          'fill-extrusion-color': '#050c12',
          'fill-extrusion-height': ['coalesce', ['get', 'render_height'], 6],
          'fill-extrusion-base': ['coalesce', ['get', 'render_min_height'], 0],
          'fill-extrusion-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.5, 14, 0.94],
          'fill-extrusion-vertical-gradient': true,
        },
      },
      {
        id: 'road-labels',
        type: 'symbol',
        source: 'omt',
        'source-layer': 'transportation_name',
        filter: cls('primary', 'secondary', 'tertiary', 'trunk', 'minor'),
        minzoom: 14.5,
        layout: {
          'symbol-placement': 'line',
          'text-field': ['upcase', ['coalesce', ['get', 'name_en'], ['get', 'name'], '']],
          'text-font': FONT,
          'text-size': ['interpolate', ['linear'], ['zoom'], 14, 8.5, 18, 12],
          'text-letter-spacing': 0.18,
          'text-max-angle': 30,
        },
        paint: { 'text-color': '#4a95ae', 'text-halo-color': '#02070b', 'text-halo-width': 1.4 },
      },
      ...['LineString', 'Point'].map((geom) => ({
        id: `water-labels-${geom}`,
        type: 'symbol',
        source: 'omt',
        'source-layer': 'water_name',
        filter: ['==', ['geometry-type'], geom],
        layout: {
          'text-field': ['upcase', ['coalesce', ['get', 'name_en'], ['get', 'name'], '']],
          'text-font': FONT_ITALIC,
          'text-size': 12,
          'text-letter-spacing': 0.4,
          'symbol-placement': geom === 'Point' ? 'point' : 'line',
        },
        paint: { 'text-color': '#3a9fcc', 'text-halo-color': '#02070b', 'text-halo-width': 1 },
      })),
      {
        id: 'station-labels',
        type: 'symbol',
        source: 'omt',
        'source-layer': 'poi',
        filter: ['all', ['==', ['get', 'class'], 'railway'], ['<=', ['coalesce', ['get', 'rank'], 99], 20]],
        minzoom: 13.5,
        layout: {
          'text-field': ['upcase', ['coalesce', ['get', 'name_en'], ['get', 'name'], '']],
          'text-font': FONT,
          'text-size': 9.5,
          'text-letter-spacing': 0.14,
          'text-offset': [0, 1.1],
          'text-anchor': 'top',
          'text-max-width': 8,
        },
        paint: { 'text-color': '#9fdcee', 'text-halo-color': '#02070b', 'text-halo-width': 1.2, 'text-opacity': 0.85 },
      },
      {
        id: 'place-minor',
        type: 'symbol',
        source: 'omt',
        'source-layer': 'place',
        filter: cls('suburb', 'neighbourhood', 'quarter'),
        minzoom: 11,
        layout: {
          'text-field': ['upcase', ['coalesce', ['get', 'name_en'], ['get', 'name'], '']],
          'text-font': FONT,
          'text-size': ['interpolate', ['linear'], ['zoom'], 11, 9, 16, 13],
          'text-letter-spacing': 0.32,
          'text-max-width': 9,
        },
        paint: { 'text-color': '#7fbfd3', 'text-halo-color': '#02070b', 'text-halo-width': 1.5, 'text-opacity': 0.8 },
      },
      {
        id: 'place-major',
        type: 'symbol',
        source: 'omt',
        'source-layer': 'place',
        filter: cls('city', 'town'),
        layout: {
          'text-field': ['upcase', ['coalesce', ['get', 'name_en'], ['get', 'name'], '']],
          'text-font': FONT_BOLD,
          'text-size': ['interpolate', ['linear'], ['zoom'], 4, 11, 10, 18],
          'text-letter-spacing': 0.45,
        },
        paint: { 'text-color': '#cfefff', 'text-halo-color': '#02070b', 'text-halo-width': 1.6 },
      },
    ],
  };
}
